module.exports.responseMessages = {
    login: 'You are successfully signed in',
    password: "Password updated successfully",
    invalidPassword: "",
    invalidConfirmPassword: "Confirm password do not matched",
    invalidUser: "You are not authorize to access",
    resetMail: "You receive mail for reset password",
    emailNotFound: "Email not found, please enter registered email",
    passwordNotMatched: "Wrong password",
    signOut: "Sign out successfully",
    aboutUsAdded: "About us details added successfully",
    agentDelete: "Agent successfully deleted",
    agentAdded: "Agent updated or added successfully",
    addBlog: "Blog added successfully",
    editBlog: "Blog updated successfully",
    finance: "Finance details added and updated successfully",
    contactUs: "Contact US details added and updated successfully",
    home: "Home details added and updated successfully",
    sell: "Sell details added and updated successfully",
    registration: "User registered successfully",
    userAlreadyExists: 'User already exists with given email',
    userUpdated: 'User successfully updated',
    userDeleted: 'User successfully deleted',
    usrNotFound: "User not found",
};